### PR TITLE
Bytestring 0.11

### PR DESCRIPTION
**Pull request by phadej**
I suggest also closing all PRs and issues in the old (bos) repository telling people to reopen issues there.

Having two repositories is very unoptimal workflow.

Travis job: https://travis-ci.org/github/bgamari/attoparsec/builds/728564255

### CODE REVIEW

**Comment by phadej** [comment]
And seems that the repositories are out-of-sync, which is even worse.

I suggest abondining `bos/attoparsec`.

**Comment by phadej** [comment]
FWIW, I suggest migrating all travis repositories to `travis-ci.com`. As you can see, the old integration is broken, as it's not reporting anything back. https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/

**Comment by phadej** [comment]
ping

**Comment by Bodigrim** [comment]
Ping @bgamari

**Comment by phadej** [comment]
Reopened in https://github.com/haskell/attoparsec/pull/172

**Pull request closed without merging**
